# Generated by Django 6.0.6 on 2026-09-25 13:09

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_level', models.CharField(help_text="Academic scope level of the user at export time (e.g. 'teacher', 'department', 'school').", max_length=50)),
                ('filters_applied', models.JSONField(default=dict, help_text='Filter parameters applied during the export.')),
                ('row_count', models.PositiveIntegerField(help_text='Total number of student records exported.')),
                ('exported_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, help_text='Timestamp when the export occurred.')),
                ('user', models.ForeignKey(help_text='User who initiated the export.', on_delete=django.db.models.deletion.CASCADE, related_name='analytics_export_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Export Audit Log',
                'verbose_name_plural': 'Export Audit Logs',
                'ordering': ['-exported_at', '-id'],
            },
        ),
    ]
