/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/api/v1/analytics/at-risk/": {
    /**
     * Get paginated roster of at-risk students
     * @description Returns paginated at-risk student records from latest prediction snapshots. Requires view_at_risk_roster capability (Faculty only; Executives receive 403).
     */
    get: operations["v1_analytics_at_risk_list"];
  };
  "/api/v1/analytics/breakdown/": {
    /**
     * Get scoped performance breakdown
     * @description Aggregates performance by level strictly below user's academic scope with differential privacy (groups < 10 merged into 'Other (hidden)').
     */
    get: operations["v1_analytics_breakdown_retrieve"];
  };
  "/api/v1/analytics/distribution/": {
    /**
     * Get score histogram distribution for a subject
     * @description Computes fixed-bin percentage score histogram for a subject within user's scope.
     */
    get: operations["v1_analytics_distribution_retrieve"];
  };
  "/api/v1/analytics/export/at-risk.csv": {
    /**
     * Export at-risk student roster as CSV
     * @description Downloads CSV export of at-risk students. Throttled to 5 exports/hour per user. Creates an audit log record.
     */
    get: operations["v1_analytics_export_at_risk.csv_retrieve"];
  };
  "/api/v1/analytics/overview/": {
    /**
     * Get institutional analytics overview KPIs
     * @description Returns top-level KPIs scoped to caller's academic role. Database-aggregated, zero student-by-student loops.
     */
    get: operations["v1_analytics_overview_retrieve"];
  };
  "/api/v1/analytics/trend/": {
    /**
     * Get longitudinal performance trend
     * @description Returns metrics per semester across academic history.
     */
    get: operations["v1_analytics_trend_retrieve"];
  };
  "/api/v1/auth/login/": {
    /**
     * Session Login
     * @description Authenticates the user and initiates an HTTP-only session cookie.
     */
    post: operations["v1_auth_login_create"];
  };
  "/api/v1/auth/logout/": {
    /**
     * Session Logout
     * @description Terminates the current user session.
     */
    post: operations["v1_auth_logout_create"];
  };
  "/api/v1/csrf/": {
    /**
     * Retrieve CSRF Token
     * @description Returns a valid CSRF token to be included in the X-CSRFToken header for unsafe requests.
     */
    get: operations["v1_csrf_retrieve"];
  };
  "/api/v1/habits/check-ins/": {
    /**
     * List Habit Check-Ins
     * @description Returns paginated history of habit check-ins for the currently authenticated student.
     */
    get: operations["v1_habits_check_ins_list"];
    /**
     * Record Habit Check-In
     * @description Submits a daily or weekly habit check-in, validated against contract boundary ranges.
     */
    post: operations["v1_habits_check_ins_create"];
  };
  "/api/v1/internal-marks/": {
    /**
     * Bulk Internal Marks Entry
     * @description Atomically updates internal marks for students in an assigned subject and batch.
     */
    post: operations["v1_internal_marks_create"];
  };
  "/api/v1/me/": {
    /**
     * Current User Context
     * @description Returns active session details, server-derived scope, and granular UI capabilities.
     */
    get: operations["v1_me_retrieve"];
  };
  "/api/v1/models/": {
    /**
     * List Model Registry Versions
     * @description Inspects registered baseline and institutional models, evaluation metrics, and active states.
     */
    get: operations["v1_models_list"];
  };
  "/api/v1/students/{id}/predictions/": {
    /**
     * Student Performance Predictions
     * @description Generates real-time score forecasts and advisory explanations for the specified student ID.
     */
    get: operations["v1_students_predictions_retrieve"];
  };
  "/api/v1/students/{id}/results/": {
    /**
     * Student Academic Results
     * @description Retrieves official semester and subject results for the specified student ID.
     */
    get: operations["v1_students_results_retrieve"];
  };
  "/api/v1/teaching-assignments/": {
    /**
     * Faculty Teaching Assignments
     * @description Lists all courses, batches, and subjects currently assigned to the authenticated teacher.
     */
    get: operations["v1_teaching_assignments_list"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    ActiveModelInfo: {
      slot: string;
      version: number;
      algorithm: string;
      metrics: {
        [key: string]: unknown;
      };
      is_active: boolean;
    };
    AnalyticsBreakdownGroup: {
      id: number | null;
      name: string;
      code: string;
      student_count: number;
      /** Format: double */
      pass_rate: number;
      /** Format: double */
      average_percentage: number;
    };
    AnalyticsBreakdownResponse: {
      by: string;
      groups: components["schemas"]["AnalyticsBreakdownGroup"][];
    };
    AnalyticsDistributionBin: {
      label: string;
      min: number;
      max: number;
      count: number;
    };
    AnalyticsDistributionResponse: {
      subject: components["schemas"]["AnalyticsDistributionSubject"];
      total_records: number;
      bins: components["schemas"]["AnalyticsDistributionBin"][];
    };
    AnalyticsDistributionSubject: {
      id: number;
      code: string;
      title: string;
    };
    AnalyticsOverview: {
      total_students: number;
      /** Format: double */
      pass_rate: number;
      /** Format: double */
      average_percentage: number;
      at_risk_count: number;
      /** Format: double */
      at_risk_rate: number;
      /** Format: double */
      published_share: number;
      model: components["schemas"]["ActiveModelInfo"] | null;
    };
    AnalyticsTrendPoint: {
      semester: number;
      /** Format: double */
      value: number;
      sample_size: number;
    };
    AnalyticsTrendResponse: {
      metric: string;
      points: components["schemas"]["AnalyticsTrendPoint"][];
    };
    AtRiskStudentRoster: {
      student_id: number;
      roll_no: string;
      name: string;
      batch_code: string;
      course_code: string;
      subject_code: string;
      semester: number;
      /** Format: double */
      predicted_percentage: number | null;
      risk_band: string;
      reasons: string[];
      /** Format: date-time */
      taken_at: string;
    };
    BulkInternalMarksRequestRequest: {
      subject_id: number;
      batch_id: number;
      marks: components["schemas"]["SingleMarkEntryRequest"][];
    };
    BulkInternalMarksResponse: {
      updated_count: number;
      detail: string;
    };
    CSRFResponse: {
      /** @description CSRF token for unsafe state-mutating requests */
      csrfToken: string;
    };
    FactorDetail: {
      feature: string;
      name: string;
      impact: string;
      direction: string;
      /** @default */
      description?: string;
    };
    HabitCheckInLog: {
      id: number;
      /** Format: date */
      log_date?: string;
      log_type?: components["schemas"]["LogTypeEnum"];
      /**
       * Format: double
       * @description Hours studied (today if daily, total for week if weekly)
       */
      hours_studied?: number;
      /**
       * Format: double
       * @description Hours slept (last night if daily, avg/night if weekly)
       */
      sleep_hours?: number;
      motivation_level?: components["schemas"]["MotivationLevelEnum"] | components["schemas"]["NullEnum"] | null;
      /** @description Tutoring sessions attended */
      tutoring_sessions?: number;
      /** @description Hours/days of physical activity or exercise */
      physical_activity?: number;
      notes?: string | null;
      /** Format: date-time */
      created_at: string;
    };
    HabitCheckInLogRequest: {
      /** Format: date */
      log_date?: string;
      log_type?: components["schemas"]["LogTypeEnum"];
      /**
       * Format: double
       * @description Hours studied (today if daily, total for week if weekly)
       */
      hours_studied?: number;
      /**
       * Format: double
       * @description Hours slept (last night if daily, avg/night if weekly)
       */
      sleep_hours?: number;
      motivation_level?: components["schemas"]["MotivationLevelEnum"] | components["schemas"]["NullEnum"] | null;
      /** @description Tutoring sessions attended */
      tutoring_sessions?: number;
      /** @description Hours/days of physical activity or exercise */
      physical_activity?: number;
      notes?: string | null;
    };
    /**
     * @description * `DAILY` - Daily Log
     * * `WEEKLY` - Weekly Log
     * @enum {string}
     */
    LogTypeEnum: "DAILY" | "WEEKLY";
    LoginRequestRequest: {
      username: string;
      password: string;
    };
    LogoutResponse: {
      /** @description Logout status message */
      detail: string;
    };
    ModelVersion: {
      id: number;
      /**
       * @description Deployment slot ('baseline' or 'institute')
       *
       * * `baseline` - Baseline (Model A)
       * * `institute` - Institute (Model B)
       */
      slot: components["schemas"]["SlotEnum"];
      /** @description Sequential version integer within the slot */
      version: number;
      /** @description Designates whether this version actively serves predictions for its slot */
      is_active?: boolean;
      /**
       * Format: date-time
       * @description Timestamp when this version was registered
       */
      created_at: string;
      /** @description Short description of dataset/cohort used for training */
      trained_on: string;
      /** @description Number of samples in training split */
      n_train_rows: number;
      /** @description Number of samples in evaluation/holdout split */
      n_test_rows: number;
      /** @description Evaluation metrics dictionary (e.g. {'rmse': 4.12, 'r2': 0.74}) */
      metrics?: unknown;
      /** @description List of input feature names in exact column order */
      feature_names?: unknown;
      /** @description Filename of serialized joblib model (must reside in MODEL_ARTIFACT_DIR) */
      artifact_file: string;
    };
    /**
     * @description * `Low` - Low
     * * `Medium` - Medium
     * * `High` - High
     * @enum {string}
     */
    MotivationLevelEnum: "Low" | "Medium" | "High";
    /** @enum {unknown} */
    NullEnum: "";
    PaginatedHabitCheckInLogList: {
      /** @example 123 */
      count: number;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=4
       */
      next?: string | null;
      /**
       * Format: uri
       * @example http://api.example.org/accounts/?page=2
       */
      previous?: string | null;
      results: components["schemas"]["HabitCheckInLog"][];
    };
    SemesterResultItem: {
      id: number;
      semester: number;
      /** Format: double */
      sgpa?: number;
      /** Format: double */
      percentage?: number;
      /**
       * Format: double
       * @description Official attendance percentage recorded by the institution (0-100). None if unrecorded.
       */
      attendance_percentage?: number | null;
      total_credits?: number;
      /** @description Final official result published by Admin. When False, held as draft until bulk release. */
      is_published?: boolean;
    };
    SingleMarkEntryRequest: {
      student_id: number;
      /** Format: decimal */
      internal_marks: string;
    };
    /**
     * @description * `baseline` - Baseline (Model A)
     * * `institute` - Institute (Model B)
     * @enum {string}
     */
    SlotEnum: "baseline" | "institute";
    StudentPredictionsResponse: {
      student_id: number;
      target_semester: number;
      predictions: components["schemas"]["SubjectPrediction"][];
    };
    StudentResults: {
      student_id: number;
      roll_number: string;
      semester_results: components["schemas"]["SemesterResultItem"][];
      subject_results: components["schemas"]["SubjectResultItem"][];
    };
    SubjectPrediction: {
      subject_code: string;
      subject_name: string;
      semester: number;
      /** Format: double */
      predicted_score: number | null;
      /** Format: double */
      confidence_score: number | null;
      risk_band: string | null;
      model_label: string;
      model_version: number | null;
      factors: components["schemas"]["FactorDetail"][];
      disclaimer: string;
      insufficient_data: boolean;
      insufficient_data_reasons: string[];
    };
    SubjectResultItem: {
      id: number;
      subject_code: string;
      subject_name: string;
      subject_credits: number;
      semester: number;
      internal_marks?: number;
      total_secured?: number;
      max_marks?: number;
      grade: string;
    };
    TeachingAssignment: {
      id: number;
      subject_id: number;
      subject_code: string;
      subject_name: string;
      internal_max: number;
      batch_id: number;
      batch_name: string;
      course_name: string;
      semester: number;
    };
    /**
     * @description Public representation of the authenticated user's session.
     * Strictly excludes email, phone number, and protected demographics.
     */
    UserMe: {
      id: number;
      display_name: string;
      role: string;
      scope_label: string;
      capabilities: readonly string[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get paginated roster of at-risk students
   * @description Returns paginated at-risk student records from latest prediction snapshots. Requires view_at_risk_roster capability (Faculty only; Executives receive 403).
   */
  v1_analytics_at_risk_list: {
    parameters: {
      query?: {
        /** @description Batch ID filter */
        batch?: number;
        /** @description Course ID filter */
        course?: number;
        /** @description Page number */
        page?: number;
        /** @description Semester number filter */
        semester?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AtRiskStudentRoster"][];
        };
      };
    };
  };
  /**
   * Get scoped performance breakdown
   * @description Aggregates performance by level strictly below user's academic scope with differential privacy (groups < 10 merged into 'Other (hidden)').
   */
  v1_analytics_breakdown_retrieve: {
    parameters: {
      query: {
        /** @description Batch ID filter */
        batch?: number;
        /** @description Breakdown level (school, department, course, batch, subject, teacher) */
        by: string;
        /** @description Course ID filter */
        course?: number;
        /** @description Department ID filter */
        department?: number;
        /** @description School ID filter */
        school?: number;
        /** @description Semester number filter */
        semester?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AnalyticsBreakdownResponse"];
        };
      };
    };
  };
  /**
   * Get score histogram distribution for a subject
   * @description Computes fixed-bin percentage score histogram for a subject within user's scope.
   */
  v1_analytics_distribution_retrieve: {
    parameters: {
      query: {
        /** @description Batch ID filter */
        batch?: number;
        /** @description Semester number filter */
        semester?: number;
        /** @description Subject ID */
        subject: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AnalyticsDistributionResponse"];
        };
      };
    };
  };
  /**
   * Export at-risk student roster as CSV
   * @description Downloads CSV export of at-risk students. Throttled to 5 exports/hour per user. Creates an audit log record.
   */
  "v1_analytics_export_at_risk.csv_retrieve": {
    parameters: {
      query?: {
        /** @description Batch ID filter */
        batch?: number;
        /** @description Course ID filter */
        course?: number;
        /** @description Semester number filter */
        semester?: number;
      };
    };
    responses: {
      /** @description CSV file download */
      200: {
        content: never;
      };
    };
  };
  /**
   * Get institutional analytics overview KPIs
   * @description Returns top-level KPIs scoped to caller's academic role. Database-aggregated, zero student-by-student loops.
   */
  v1_analytics_overview_retrieve: {
    parameters: {
      query?: {
        /** @description Batch ID filter */
        batch?: number;
        /** @description Course ID filter */
        course?: number;
        /** @description Department ID filter */
        department?: number;
        /** @description School ID filter */
        school?: number;
        /** @description Semester number filter */
        semester?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AnalyticsOverview"];
        };
      };
    };
  };
  /**
   * Get longitudinal performance trend
   * @description Returns metrics per semester across academic history.
   */
  v1_analytics_trend_retrieve: {
    parameters: {
      query: {
        /** @description Batch ID filter */
        batch?: number;
        /** @description Course ID filter */
        course?: number;
        /** @description Department ID filter */
        department?: number;
        /** @description Metric: pass_rate, avg_percentage, at_risk_rate */
        metric: string;
        /** @description School ID filter */
        school?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["AnalyticsTrendResponse"];
        };
      };
    };
  };
  /**
   * Session Login
   * @description Authenticates the user and initiates an HTTP-only session cookie.
   */
  v1_auth_login_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["LoginRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["LoginRequestRequest"];
        "multipart/form-data": components["schemas"]["LoginRequestRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserMe"];
        };
      };
      /** @description Invalid username or password / inactive account */
      400: {
        content: never;
      };
    };
  };
  /**
   * Session Logout
   * @description Terminates the current user session.
   */
  v1_auth_logout_create: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["LogoutResponse"];
        };
      };
    };
  };
  /**
   * Retrieve CSRF Token
   * @description Returns a valid CSRF token to be included in the X-CSRFToken header for unsafe requests.
   */
  v1_csrf_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["CSRFResponse"];
        };
      };
    };
  };
  /**
   * List Habit Check-Ins
   * @description Returns paginated history of habit check-ins for the currently authenticated student.
   */
  v1_habits_check_ins_list: {
    parameters: {
      query?: {
        /** @description A page number within the paginated result set. */
        page?: number;
        /** @description Number of results to return per page. */
        page_size?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["PaginatedHabitCheckInLogList"];
        };
      };
    };
  };
  /**
   * Record Habit Check-In
   * @description Submits a daily or weekly habit check-in, validated against contract boundary ranges.
   */
  v1_habits_check_ins_create: {
    requestBody?: {
      content: {
        "application/json": components["schemas"]["HabitCheckInLogRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["HabitCheckInLogRequest"];
        "multipart/form-data": components["schemas"]["HabitCheckInLogRequest"];
      };
    };
    responses: {
      201: {
        content: {
          "application/json": components["schemas"]["HabitCheckInLog"];
        };
      };
      /** @description Input range validation failed */
      400: {
        content: never;
      };
    };
  };
  /**
   * Bulk Internal Marks Entry
   * @description Atomically updates internal marks for students in an assigned subject and batch.
   */
  v1_internal_marks_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["BulkInternalMarksRequestRequest"];
        "application/x-www-form-urlencoded": components["schemas"]["BulkInternalMarksRequestRequest"];
        "multipart/form-data": components["schemas"]["BulkInternalMarksRequestRequest"];
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["BulkInternalMarksResponse"];
        };
      };
      /** @description Per-row validation error report */
      400: {
        content: never;
      };
      /** @description Teacher is not assigned to this subject and batch */
      403: {
        content: never;
      };
    };
  };
  /**
   * Current User Context
   * @description Returns active session details, server-derived scope, and granular UI capabilities.
   */
  v1_me_retrieve: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["UserMe"];
        };
      };
    };
  };
  /**
   * List Model Registry Versions
   * @description Inspects registered baseline and institutional models, evaluation metrics, and active states.
   */
  v1_models_list: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["ModelVersion"][];
        };
      };
    };
  };
  /**
   * Student Performance Predictions
   * @description Generates real-time score forecasts and advisory explanations for the specified student ID.
   */
  v1_students_predictions_retrieve: {
    parameters: {
      query?: {
        /** @description Target semester (defaults to current) */
        semester?: number;
      };
      path: {
        /** @description Student ID */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["StudentPredictionsResponse"];
        };
      };
      /** @description Access denied: outside user scope */
      403: {
        content: never;
      };
      /** @description Student not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Student Academic Results
   * @description Retrieves official semester and subject results for the specified student ID.
   */
  v1_students_results_retrieve: {
    parameters: {
      path: {
        /** @description Student ID */
        id: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["StudentResults"];
        };
      };
      /** @description Access denied: outside user scope */
      403: {
        content: never;
      };
      /** @description Student not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Faculty Teaching Assignments
   * @description Lists all courses, batches, and subjects currently assigned to the authenticated teacher.
   */
  v1_teaching_assignments_list: {
    responses: {
      200: {
        content: {
          "application/json": components["schemas"]["TeachingAssignment"][];
        };
      };
    };
  };
}
