# Generated by Django 6.0.6 on 2026-08-22 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_university_batch_current_study_year_batch_strength_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterresult',
            name='attendance_percentage',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='extracurricular_activities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='hours_studied_per_week',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='motivation_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='parental_involvement',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='peer_influence',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='physical_activity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='sleep_hours_per_night',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='semesterresult',
            name='tutoring_sessions',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='access_to_resources',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='distance_from_home',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='family_income',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='internet_access',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='learning_disabilities',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='parental_education_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
