# Generated by Django 6.0.6 on 2026-09-24 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_semesterresult_is_published_internalassessment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentprofile',
            name='data_origin',
            field=models.CharField(choices=[('demo', 'Demo'), ('real', 'Real')], db_index=True, default='real', help_text='Tracks whether student record is synthetic demo data or real institutional data.', max_length=10),
        ),
    ]
