# Generated by Django 6.0.6 on 2026-09-24 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_studentprofile_data_origin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semesterresult',
            name='attendance_percentage',
            field=models.FloatField(blank=True, default=None, help_text='Official attendance percentage recorded by the institution (0-100). None if unrecorded.', null=True),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='extracurricular_activities',
            field=models.BooleanField(blank=True, default=None, help_text='Official participation status in extracurricular activities. None if unrecorded.', null=True),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='hours_studied_per_week',
            field=models.FloatField(blank=True, default=None, help_text='Official study hours per week. None if unrecorded.', null=True),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='motivation_level',
            field=models.CharField(blank=True, default=None, help_text="Official motivation level ('Low', 'Medium', 'High'). None if unrecorded.", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='parental_involvement',
            field=models.CharField(blank=True, default=None, help_text='Official parental involvement level. None if unrecorded.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='peer_influence',
            field=models.CharField(blank=True, default=None, help_text='Official peer influence level. None if unrecorded.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='physical_activity',
            field=models.IntegerField(blank=True, default=None, help_text='Official physical activity days/hours per week. None if unrecorded.', null=True),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='sleep_hours_per_night',
            field=models.FloatField(blank=True, default=None, help_text='Official sleep hours per night. None if unrecorded.', null=True),
        ),
        migrations.AlterField(
            model_name='semesterresult',
            name='tutoring_sessions',
            field=models.IntegerField(blank=True, default=None, help_text='Official count of tutoring sessions attended. None if unrecorded.', null=True),
        ),
    ]
