# Generated by Django 6.0.6 on 2026-09-25 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0007_alter_semesterresult_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='habitcheckinlog',
            index=models.Index(fields=['student', 'log_date'], name='idx_habitlog_student_date'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['student', 'semester'], name='idx_result_student_sem'),
        ),
        migrations.AddIndex(
            model_name='result',
            index=models.Index(fields=['subject', 'semester'], name='idx_result_subject_sem'),
        ),
        migrations.AddIndex(
            model_name='semesterresult',
            index=models.Index(fields=['is_published', 'semester'], name='idx_semresult_pub_sem'),
        ),
        migrations.AddConstraint(
            model_name='habitcheckinlog',
            constraint=models.CheckConstraint(condition=models.Q(('sleep_hours__gte', 0.0), ('sleep_hours__lte', 24.0)), name='check_habit_log_sleep_hours_range'),
        ),
        migrations.AddConstraint(
            model_name='habitcheckinlog',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('log_type', 'DAILY'), ('hours_studied__gte', 0.0), ('hours_studied__lte', 24.0)), models.Q(('log_type', 'WEEKLY'), ('hours_studied__gte', 0.0), ('hours_studied__lte', 168.0)), _connector='OR'), name='check_habit_log_hours_studied_range'),
        ),
        migrations.AddConstraint(
            model_name='result',
            constraint=models.CheckConstraint(condition=models.Q(('total_secured__gte', 0), ('total_secured__lte', models.F('max_marks')), ('max_marks__gt', 0)), name='check_result_total_secured_range'),
        ),
        migrations.AddConstraint(
            model_name='semesterresult',
            constraint=models.CheckConstraint(condition=models.Q(('percentage__gte', 0.0), ('percentage__lte', 100.0)), name='check_semester_result_percentage_range'),
        ),
        migrations.AddConstraint(
            model_name='semesterresult',
            constraint=models.CheckConstraint(condition=models.Q(('attendance_percentage__isnull', True), models.Q(('attendance_percentage__gte', 0.0), ('attendance_percentage__lte', 100.0)), _connector='OR'), name='check_semester_result_attendance_range'),
        ),
        migrations.AddConstraint(
            model_name='semesterresult',
            constraint=models.CheckConstraint(condition=models.Q(('sleep_hours_per_night__isnull', True), models.Q(('sleep_hours_per_night__gte', 0.0), ('sleep_hours_per_night__lte', 24.0)), _connector='OR'), name='check_semester_result_sleep_range'),
        ),
        migrations.AddConstraint(
            model_name='semesterresult',
            constraint=models.CheckConstraint(condition=models.Q(('hours_studied_per_week__isnull', True), models.Q(('hours_studied_per_week__gte', 0.0), ('hours_studied_per_week__lte', 168.0)), _connector='OR'), name='check_semester_result_study_hours_range'),
        ),
    ]
