# Generated by Django 6.0.6 on 2026-06-11 08:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('established_year', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='batch',
            name='current_study_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='batch',
            name='strength',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='department',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hod_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='result',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='results', to='academics.batch'),
        ),
        migrations.AddField(
            model_name='result',
            name='credit_points',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='result',
            name='declaration_date',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='school',
            name='dean',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dean_of', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='admission_type',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='current_year',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='expected_graduation_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='guardian_relation',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='registration_no',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='subject',
            name='external_max',
            field=models.IntegerField(default=70),
        ),
        migrations.AddField(
            model_name='subject',
            name='internal_max',
            field=models.IntegerField(default=30),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='employment_type',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='qualification',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='teacherprofile',
            name='specialization',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.batch'),
        ),
        migrations.AlterField(
            model_name='studentprofile',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='academics.course'),
        ),
        migrations.AlterField(
            model_name='teacherprofile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teachers', to='academics.department'),
        ),
        migrations.CreateModel(
            name='TeachingAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_session', models.CharField(blank=True, max_length=30)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.batch')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='academics.teacherprofile')),
            ],
        ),
        migrations.AddField(
            model_name='school',
            name='university',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='academics.university'),
        ),
        migrations.CreateModel(
            name='SemesterResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField()),
                ('total_max', models.IntegerField(default=0)),
                ('total_secured', models.IntegerField(default=0)),
                ('total_credits', models.IntegerField(default=0)),
                ('total_credit_points', models.FloatField(default=0)),
                ('percentage', models.FloatField(default=0)),
                ('sgpa', models.FloatField(default=0)),
                ('result_status', models.CharField(blank=True, max_length=10)),
                ('gc_no', models.CharField(blank=True, max_length=20)),
                ('exam_session', models.CharField(blank=True, max_length=30)),
                ('declaration_date', models.CharField(blank=True, max_length=20)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_results', to='academics.studentprofile')),
            ],
            options={
                'unique_together': {('student', 'semester')},
            },
        ),
    ]
