# Generated by Django 6.0.6 on 2026-09-04 17:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_semesterresult_attendance_percentage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HabitCheckInLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('DAILY', 'Daily Log'), ('WEEKLY', 'Weekly Log')], default='DAILY', max_length=10)),
                ('log_date', models.DateField(default=django.utils.timezone.now)),
                ('hours_studied', models.FloatField(default=0.0, help_text='Hours studied (today if daily, total for week if weekly)')),
                ('sleep_hours', models.FloatField(default=7.0, help_text='Hours slept (last night if daily, avg/night if weekly)')),
                ('motivation_level', models.CharField(choices=[('Low', 'Low'), ('Medium', 'Medium'), ('High', 'High')], default='Medium', max_length=10)),
                ('tutoring_sessions', models.IntegerField(default=0, help_text='Tutoring sessions attended')),
                ('physical_activity', models.IntegerField(default=0, help_text='Hours/days of physical activity or exercise')),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habit_logs', to='academics.studentprofile')),
            ],
            options={
                'ordering': ['-log_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentHabitPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('DAILY', 'Daily Quick-Check (30 sec)'), ('WEEKLY', 'Weekly Summary (2 min)')], default='DAILY', max_length=10)),
                ('streak_count', models.IntegerField(default=0)),
                ('last_checkin_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='habit_preference', to='academics.studentprofile')),
            ],
        ),
    ]
