# Generated by Django 6.0.6 on 2026-09-05 14:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_habitcheckinlog_studenthabitpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='semesterresult',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Final official result published by Admin. When False, held as draft until bulk release.'),
        ),
        migrations.CreateModel(
            name='InternalAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.IntegerField(default=1)),
                ('title', models.CharField(help_text='e.g. Midterm Test 1, Assignment 2', max_length=100)),
                ('assessment_type', models.CharField(choices=[('MIDTERM', 'Mid-Semester Examination'), ('ASSIGNMENT', 'Continuous Assignment'), ('QUIZ', 'Class Test / Quiz'), ('LAB', 'Practical / Lab Assessment'), ('PROJECT', 'Term Project / Seminar')], default='ASSIGNMENT', max_length=20)),
                ('marks_obtained', models.FloatField(default=0.0)),
                ('max_marks', models.FloatField(default=25.0)),
                ('date_conducted', models.DateField(default=django.utils.timezone.now)),
                ('is_submitted', models.BooleanField(default=True, help_text='Visible across hierarchical scope when submitted')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_assessments', to='academics.batch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_assessments', to='academics.studentprofile')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_assessments', to='academics.subject')),
                ('teacher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_assessments', to='academics.teacherprofile')),
            ],
            options={
                'ordering': ['-date_conducted', '-created_at'],
            },
        ),
    ]
